name: myapp
description: "A Music project..."
publish_to: 'none'
version: 0.4.8+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Añadido para solucionar el error de MaterialLocalizations
    sdk: flutter

  cupertino_icons: ^1.0.8
  youtube_explode_dart: ^3.0.5 # Usamos la original
  youtube_explode_dart_plus: ^1.0.3
  path_provider: ^2.1.5
  just_audio:
    path: third_party/just_audio_patched
  audio_session: ^0.2.2
  permission_handler: ^12.0.1
  path: ^1.9.1
  audio_service: ^0.18.18
  provider: ^6.0.0 # Añadido para gestionar el estado del reproductor minimizable
  google_fonts: ^6.3.3
  go_router: ^17.0.1
  video_player: ^2.10.1
  chewie: ^1.13.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  dio: ^5.9.0
  collection: ^1.19.1
  palette_generator: ^0.3.3+7
  image: ^4.5.4
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.5
  share_plus: ^11.1.0
  flutter_slidable: ^3.1.2
  flutter_cache_manager: ^3.4.1
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  cupertino_context_menu_plus: ^1.0.3
  supabase_flutter: ^2.10.4
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4

# Anulación correcta:
# Forzamos a todo el proyecto (incluyendo las dependencias de youtube_player_flutter)
# a usar la versión 3.0.5 de youtube_explode_dart.
dependency_overrides:
  youtube_explode_dart: ^3.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/iconloadscreen.png
    - assets/airpodsicon.png
    - assets/airpodsdarkicon.png
    - assets/airpodsproicon.png
    - assets/airpodsprodarkicon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.jpg
  remove_alpha_ios: true
