const express = require("express");
const cors = require("cors");
const ytdl = require("@distube/ytdl-core");
const fs = require("node:fs");
const fsp = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");
const crypto = require("node:crypto");
const { spawn } = require("node:child_process");
const { Readable } = require("node:stream");

const app = express();
app.set("trust proxy", true);

const PORT = Number(process.env.PORT || 10000);
const API_KEY = (process.env.RESOLVER_API_KEY || "").trim();
const YTDLP_BINARY_ENV = (process.env.YTDLP_BINARY || "yt-dlp").trim();
const YTDLP_TIMEOUT_MS = Number(process.env.YTDLP_TIMEOUT_MS || 20 * 1000);
const YOUTUBE_COOKIE = (process.env.YOUTUBE_COOKIE || "").trim();
const YOUTUBE_COOKIES_FILE = (process.env.YOUTUBE_COOKIES_FILE || "").trim();
const YOUTUBE_COOKIES_B64 = (process.env.YOUTUBE_COOKIES_B64 || "").trim();
const YTDLP_PO_TOKEN = (process.env.YTDLP_PO_TOKEN || "").trim();
const YTDLP_PO_TOKEN_CLIENT = (
  process.env.YTDLP_PO_TOKEN_CLIENT || "mweb"
)
  .trim()
  .toLowerCase();
const YTDLP_VISITOR_DATA = (process.env.YTDLP_VISITOR_DATA || "").trim();
const YTDLP_PROXY_URL = (process.env.YTDLP_PROXY_URL || "").trim();
const YTDLP_PROXY_POOL = (process.env.YTDLP_PROXY_POOL || "")
  .split(",")
  .map((value) => value.trim())
  .filter(Boolean);
const YTDLP_CLIENT_PROFILES = (
  process.env.YTDLP_CLIENT_PROFILES ||
  "default,mweb,web_safari,android,web,tv_embedded,web_creator"
)
  .split(",")
  .map((value) => value.trim().toLowerCase())
  .filter(Boolean);
const YTDLP_MAX_ATTEMPTS = Math.max(
  1,
  Number(process.env.YTDLP_MAX_ATTEMPTS || 10)
);
const RESOLVE_CACHE_TTL_MS = Number(
  process.env.RESOLVE_CACHE_TTL_MS || 10 * 60 * 1000
);
const RESOLVE_BATCH_LIMIT = Number(process.env.RESOLVE_BATCH_LIMIT || 20);
const CORS_ALLOW_ORIGINS = (process.env.CORS_ALLOW_ORIGINS || "").trim();
const STEMS_ROOT = path.resolve(
  process.env.STEMS_ROOT || path.join(os.tmpdir(), "vmmusic-stems")
);
const STEMS_MODEL = (process.env.STEMS_MODEL || "htdemucs_ft").trim();
const STEMS_PYTHON = (process.env.STEMS_PYTHON || "python3").trim();
const STEMS_TIMEOUT_MS = Number(process.env.STEMS_TIMEOUT_MS || 12 * 60 * 1000);
const DART_BINARY = (process.env.DART_BINARY || "dart").trim();
const YTEXPLODE_DART_TIMEOUT_MS = Number(
  process.env.YTEXPLODE_DART_TIMEOUT_MS || 30 * 1000
);
const COVER_ANIMATION_PROXY_URL = (
  process.env.COVER_ANIMATION_PROXY_URL || ""
).trim();
const COVER_ANIMATION_PROXY_KEY = (
  process.env.COVER_ANIMATION_PROXY_KEY || ""
).trim();
const COVER_ANIMATION_TIMEOUT_MS = Number(
  process.env.COVER_ANIMATION_TIMEOUT_MS || 90 * 1000
);
const startedAt = new Date();
const resolveCache = new Map();
const YTDLP_LOCAL_BINARY = path.join(__dirname, ".bin", "yt-dlp");
const YTEXPLODE_DART_ROOT = path.resolve(__dirname, "dart_resolver");
const YTEXPLODE_DART_SCRIPT = path.join(
  YTEXPLODE_DART_ROOT,
  "bin",
  "yt_resolve.dart"
);
const YTDLP_BINARY =
  YTDLP_BINARY_ENV === "yt-dlp" && fs.existsSync(YTDLP_LOCAL_BINARY)
    ? YTDLP_LOCAL_BINARY
    : YTDLP_BINARY_ENV;
const YTDLP_PROXIES = (() => {
  const list = [];
  if (YTDLP_PROXY_URL) list.push(YTDLP_PROXY_URL);
  for (const proxy of YTDLP_PROXY_POOL) {
    if (!list.includes(proxy)) list.push(proxy);
  }
  return list;
})();
const YTDLP_MIN_PROFILES = ["default", "mweb", "web", "android", "tv_embedded"];

function buildYtDlpProfiles() {
  const merged = [...YTDLP_CLIENT_PROFILES];
  for (const profile of YTDLP_MIN_PROFILES) {
    if (!merged.includes(profile)) merged.push(profile);
  }
  return merged;
}

function parseCookieHeader(rawCookie) {
  const raw = String(rawCookie || "")
    .trim()
    .replace(/^cookie:\s*/i, "");
  if (!raw) return [];
  const cookieAttributes = new Set([
    "domain",
    "path",
    "expires",
    "max-age",
    "samesite",
    "secure",
    "httponly",
    "priority",
    "partitioned",
  ]);
  const parts = raw
    .replace(/\r?\n/g, ";")
    .split(";")
    .map((part) => part.trim())
    .filter(Boolean);
  const cookies = [];
  for (const part of parts) {
    const idx = part.indexOf("=");
    if (idx <= 0) continue;
    const name = part.slice(0, idx).trim();
    const value = part.slice(idx + 1).trim();
    if (!name || !value) continue;
    if (cookieAttributes.has(name.toLowerCase())) continue;
    if (name.startsWith("$")) continue;
    cookies.push({
      name,
      value,
      domain: ".youtube.com",
      path: "/",
      secure: true,
      httpOnly: false,
    });
  }
  return cookies;
}

async function writeYtDlpCookiesFile() {
  if (!YTDL_COOKIES.length) return null;
  const fileName = `vmmusic-yt-cookies-${process.pid}-${Date.now()}-${Math.random()
    .toString(16)
    .slice(2)}.txt`;
  const filePath = path.join(os.tmpdir(), fileName);
  const header = [
    "# Netscape HTTP Cookie File",
    "# This file is generated by vmmusic backend.",
    "",
  ].join("\n");
  const lines = YTDL_COOKIES.map((cookie) => {
    const domain = String(cookie?.domain || ".youtube.com").trim() || ".youtube.com";
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const pathValue = String(cookie?.path || "/").trim() || "/";
    const secure = cookie?.secure ? "TRUE" : "FALSE";
    const expires = "0";
    const name = String(cookie?.name || "").trim();
    const value = String(cookie?.value || "").trim();
    return `${domain}\t${includeSubdomains}\t${pathValue}\t${secure}\t${expires}\t${name}\t${value}`;
  });
  const content = `${header}${lines.join("\n")}\n`;
  await fsp.writeFile(filePath, content, "utf8");
  return filePath;
}

async function writeYtDlpCookiesFileFromBase64() {
  if (!YOUTUBE_COOKIES_B64) return null;
  const fileName = `vmmusic-yt-browser-cookies-${process.pid}-${Date.now()}-${Math.random()
    .toString(16)
    .slice(2)}.txt`;
  const filePath = path.join(os.tmpdir(), fileName);
  const cleaned = YOUTUBE_COOKIES_B64.replace(/\s+/g, "");
  const decoded = Buffer.from(cleaned, "base64").toString("utf8");
  const firstLine = String(decoded.split(/\r?\n/, 1)[0] || "").trim();
  const validHeader =
    firstLine === "# Netscape HTTP Cookie File" ||
    firstLine === "# HTTP Cookie File";
  if (!validHeader) {
    throw new Error(
      `invalid_cookies_file_header: expected Netscape header, got="${firstLine}"`
    );
  }
  await fsp.writeFile(filePath, decoded, "utf8");
  return filePath;
}

async function resolveYtDlpCookiesSource() {
  if (YOUTUBE_COOKIES_FILE) {
    // eslint-disable-next-line no-console
    console.info("[resolver] yt-dlp cookies source=file");
    return { filePath: YOUTUBE_COOKIES_FILE, ephemeral: false, source: "file" };
  }

  if (YOUTUBE_COOKIES_B64) {
    try {
      const filePath = await writeYtDlpCookiesFileFromBase64();
      if (filePath) {
        // eslint-disable-next-line no-console
        console.info("[resolver] yt-dlp cookies source=base64");
        return { filePath, ephemeral: true, source: "base64" };
      }
    } catch (error) {
      // eslint-disable-next-line no-console
      console.warn(
        `[resolver] failed to decode YOUTUBE_COOKIES_B64: ${String(error?.message || error)}`
      );
    }
  }

  const headerFile = await writeYtDlpCookiesFile();
  if (headerFile) {
    // eslint-disable-next-line no-console
    console.info("[resolver] yt-dlp cookies source=header");
    return { filePath: headerFile, ephemeral: true, source: "header" };
  }
  // eslint-disable-next-line no-console
  console.warn("[resolver] yt-dlp cookies source=none");
  return null;
}

const YTDL_COOKIES = parseCookieHeader(YOUTUBE_COOKIE);
const YTDL_AGENT = YTDL_COOKIES.length ? ytdl.createAgent(YTDL_COOKIES) : null;
if (
  !YOUTUBE_COOKIES_FILE &&
  !YOUTUBE_COOKIES_B64 &&
  YOUTUBE_COOKIE &&
  YTDL_COOKIES.length === 0
) {
  // eslint-disable-next-line no-console
  console.warn(
    "[resolver] YOUTUBE_COOKIE is set but no valid cookie pairs were parsed. Expected format: name=value; name2=value2"
  );
}
// eslint-disable-next-line no-console
console.info(
  `[resolver] startup ytProfiles=${buildYtDlpProfiles().join(",")} maxAttempts=${YTDLP_MAX_ATTEMPTS} hasPoToken=${Boolean(
    YTDLP_PO_TOKEN
  )} poTokenClient=${YTDLP_PO_TOKEN_CLIENT || "none"} hasVisitorData=${Boolean(
    YTDLP_VISITOR_DATA
  )} proxies=${YTDLP_PROXIES.length} youtubeExplodeDartScript=${fs.existsSync(
    YTEXPLODE_DART_SCRIPT
  )}`
);

const allowedOrigins = CORS_ALLOW_ORIGINS
  ? CORS_ALLOW_ORIGINS.split(",")
      .map((value) => value.trim())
      .filter(Boolean)
  : [];

app.use(
  cors({
    origin(origin, callback) {
      if (!origin || allowedOrigins.length === 0 || allowedOrigins.includes(origin)) {
        return callback(null, true);
      }
      return callback(new Error("cors_not_allowed"));
    },
  })
);
app.use(express.json({ limit: "2mb" }));
app.use("/stems-files", express.static(STEMS_ROOT));

function authMiddleware(req, res, next) {
  if (!API_KEY) return next();
  const incoming = (req.header("x-api-key") || "").trim();
  if (incoming !== API_KEY) {
    return res.status(401).json({ ok: false, error: "unauthorized" });
  }
  return next();
}

function isValidVideoId(videoId) {
  return /^[a-zA-Z0-9_-]{11}$/.test(String(videoId || "").trim());
}

async function runYoutubeExplodeDart(videoId) {
  if (!fs.existsSync(YTEXPLODE_DART_SCRIPT)) {
    const err = new Error("youtube_explode_dart_script_missing");
    err.code = "youtube_explode_dart_script_missing";
    throw err;
  }
  return await new Promise((resolve, reject) => {
    const args = [
      "--disable-analytics",
      "run",
      "bin/yt_resolve.dart",
      "--video-id",
      videoId,
    ];
    const child = spawn(DART_BINARY, args, {
      cwd: YTEXPLODE_DART_ROOT,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      const err = new Error("youtube_explode_dart_timeout");
      err.code = "youtube_explode_dart_timeout";
      reject(err);
    }, YTEXPLODE_DART_TIMEOUT_MS);

    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString("utf8");
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString("utf8");
    });
    child.on("error", (err) => {
      clearTimeout(timer);
      reject(err);
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      const lines = String(stdout || "")
        .trim()
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter(Boolean);
      const raw = lines.length ? lines[lines.length - 1] : "";
      if (code !== 0) {
        reject(
          new Error(
            `youtube_explode_dart_failed_${code}: ${
              raw || stderr || stdout || "no_output"
            }`
          )
        );
        return;
      }
      try {
        const parsed = JSON.parse(raw);
        resolve(parsed);
      } catch (error) {
        reject(
          new Error(
            `youtube_explode_dart_parse_failed: ${String(
              error?.message || error
            )} | raw=${raw || stderr || stdout || "empty"}`
          )
        );
      }
    });
  });
}

async function getExplodeInfo(videoId) {
  const data = await runYoutubeExplodeDart(videoId);
  if (!data || data.ok !== true) {
    const err = new Error("youtube_explode_dart_info_failed");
    err.code = String(data?.error || "youtube_explode_dart_info_failed");
    err.detail = String(data?.detail || data?.error || "unknown");
    throw err;
  }
  return data;
}

async function resolveWithYoutubeExplode(videoId) {
  const data = await runYoutubeExplodeDart(videoId);
  if (!data || data.ok !== true) {
    const err = new Error("no_playable_formats");
    err.code = "no_playable_formats";
    err.detail = String(
      data?.detail || data?.error || "youtube_explode_dart_no_playable_formats"
    );
    throw err;
  }
  return {
    resolver: String(data.resolver || "youtube_explode_dart"),
    videoId,
    sourceUrl: String(data.sourceUrl || "").trim(),
    isVideoSource: data.isVideoSource === true,
    audio: data.audio || null,
    muxed: data.muxed || null,
    title: data.title || null,
    author: data.author || null,
  };
}

function pickAudioFormat(formats) {
  const audios = formats.filter(
    (f) =>
      f.hasAudio &&
      !f.hasVideo &&
      typeof f.url === "string" &&
      f.url.length > 0
  );
  if (!audios.length) return null;
  audios.sort((a, b) => {
    const aContainer = String(a?.container || "").toLowerCase();
    const bContainer = String(b?.container || "").toLowerCase();
    const aPreferred = aContainer === "m4a" || aContainer === "mp4" ? 1 : 0;
    const bPreferred = bContainer === "m4a" || bContainer === "mp4" ? 1 : 0;
    if (aPreferred !== bPreferred) return bPreferred - aPreferred;
    return (b.audioBitrate || 0) - (a.audioBitrate || 0);
  });
  return audios[0];
}

function pickMuxedFormat(formats) {
  const muxed = formats.filter(
    (f) =>
      f.hasAudio &&
      f.hasVideo &&
      typeof f.url === "string" &&
      f.url.length > 0
  );
  if (!muxed.length) return null;
  muxed.sort((a, b) => (b.bitrate || 0) - (a.bitrate || 0));
  const mp4 = muxed.find((f) => (f.container || "").toLowerCase() === "mp4");
  return mp4 || muxed[0];
}

function pickYtDlpAudioFormat(formats) {
  const list = Array.isArray(formats) ? formats : [];
  const audios = list.filter((f) => {
    const acodec = String(f?.acodec || "").toLowerCase();
    const vcodec = String(f?.vcodec || "").toLowerCase();
    const url = String(f?.url || "").trim();
    return url && acodec && acodec !== "none" && (!vcodec || vcodec === "none");
  });
  if (!audios.length) return null;
  audios.sort((a, b) => {
    const aExt = String(a?.ext || "").toLowerCase();
    const bExt = String(b?.ext || "").toLowerCase();
    const aPreferred = aExt === "m4a" || aExt === "mp4" ? 1 : 0;
    const bPreferred = bExt === "m4a" || bExt === "mp4" ? 1 : 0;
    if (aPreferred !== bPreferred) return bPreferred - aPreferred;
    return (Number(b?.abr || 0) || 0) - (Number(a?.abr || 0) || 0);
  });
  return audios[0];
}

function pickYtDlpMuxedFormat(formats) {
  const list = Array.isArray(formats) ? formats : [];
  const muxed = list.filter((f) => {
    const acodec = String(f?.acodec || "").toLowerCase();
    const vcodec = String(f?.vcodec || "").toLowerCase();
    const url = String(f?.url || "").trim();
    return url && acodec && acodec !== "none" && vcodec && vcodec !== "none";
  });
  if (!muxed.length) return null;
  muxed.sort((a, b) => (Number(b?.tbr || 0) || 0) - (Number(a?.tbr || 0) || 0));
  const mp4 = muxed.find((f) =>
    String(f?.ext || "")
      .toLowerCase()
      .includes("mp4")
  );
  return mp4 || muxed[0];
}

function readCachedResolve(videoId) {
  const entry = resolveCache.get(videoId);
  if (!entry) return null;
  if (entry.expiresAt <= Date.now()) {
    resolveCache.delete(videoId);
    return null;
  }
  return entry.payload;
}

function writeCachedResolve(videoId, payload) {
  if (RESOLVE_CACHE_TTL_MS <= 0) return;
  resolveCache.set(videoId, {
    payload,
    expiresAt: Date.now() + RESOLVE_CACHE_TTL_MS,
  });
}

function parseVideoIds(input) {
  if (!Array.isArray(input)) return [];
  const unique = new Set();
  for (const item of input) {
    const id = String(item || "").trim();
    if (!id || !isValidVideoId(id)) continue;
    unique.add(id);
    if (unique.size >= RESOLVE_BATCH_LIMIT) break;
  }
  return Array.from(unique);
}

function ytDlpPlayerClientForProfile(profile) {
  switch (profile) {
    case "mweb":
      return "mweb";
    case "web_safari":
      return "web_safari";
    case "android":
      return "android";
    case "web":
      return "web";
    case "tv":
    case "tv_embedded":
      return "tv_embedded";
    case "web_creator":
      return "web_creator";
    case "ios":
      return "ios";
    case "android_vr":
      return "android_vr";
    default:
      return null;
  }
}

function ytDlpExtractorArgsForProfile(profile) {
  const args = [];
  const playerClient = ytDlpPlayerClientForProfile(profile);
  if (playerClient) {
    args.push(`player_client=${playerClient}`);
  }
  if (YTDLP_PO_TOKEN) {
    const tokenClient = YTDLP_PO_TOKEN_CLIENT || playerClient || "mweb";
    args.push(`po_token=${tokenClient}+${YTDLP_PO_TOKEN}`);
  }
  if (YTDLP_VISITOR_DATA) {
    args.push(`visitor_data=${YTDLP_VISITOR_DATA}`);
  }
  if (!args.length) return null;
  return `youtube:${args.join(";")}`;
}

async function runYtDlpJson(videoId, profile = "default", proxyUrl = null) {
  const url = `https://www.youtube.com/watch?v=${videoId}`;
  const args = [
    "--ignore-config",
    "-J",
    "--no-playlist",
    "--no-warnings",
    "--skip-download",
    "--geo-bypass",
    "--geo-bypass-country",
    "US",
    url,
  ];
  const extractorArgs = ytDlpExtractorArgsForProfile(profile);
  if (extractorArgs) {
    args.unshift(extractorArgs);
    args.unshift("--extractor-args");
  }
  if (proxyUrl) {
    args.unshift(proxyUrl);
    args.unshift("--proxy");
  }
  const cookiesSource = await resolveYtDlpCookiesSource();
  const cookiesFile = cookiesSource?.filePath || null;
  if (cookiesFile) {
    args.unshift(cookiesFile);
    args.unshift("--cookies");
  }
  return await new Promise((resolve, reject) => {
    const child = spawn(YTDLP_BINARY, args, {
      cwd: __dirname,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let settled = false;
    const finalize = (handler) => (value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (cookiesFile && cookiesSource?.ephemeral) {
        void fsp.unlink(cookiesFile).catch(() => {});
      }
      handler(value);
    };
    const safeResolve = finalize(resolve);
    const safeReject = finalize(reject);
    let stdout = "";
    let stderr = "";
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      safeReject(new Error("yt_dlp_timeout"));
    }, YTDLP_TIMEOUT_MS);
    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString("utf8");
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString("utf8");
    });
    child.on("error", (err) => {
      safeReject(err);
    });
    child.on("close", (code) => {
      if (code !== 0) {
        safeReject(new Error(`yt_dlp_failed_${code}: ${stderr || stdout}`));
        return;
      }
      try {
        const parsed = JSON.parse(stdout.trim());
        safeResolve(parsed);
      } catch (e) {
        safeReject(new Error(`yt_dlp_output_parse_failed: ${String(e)}`));
      }
    });
  });
}

async function resolveWithYtDlp(videoId) {
  const profiles = buildYtDlpProfiles();
  const proxies = YTDLP_PROXIES.length ? [null, ...YTDLP_PROXIES] : [null];
  const attempts = [];
  for (const profile of profiles) {
    for (const proxy of proxies) {
      attempts.push({ profile, proxy });
    }
  }

  const errors = [];
  const limitedAttempts = attempts.slice(0, YTDLP_MAX_ATTEMPTS);
  for (const attempt of limitedAttempts) {
    const { profile, proxy } = attempt;
    // eslint-disable-next-line no-console
    console.info(
      `[resolver] yt-dlp attempt videoId=${videoId} profile=${profile} proxy=${proxy || "none"}`
    );
    try {
      const info = await runYtDlpJson(videoId, profile, proxy);
      const formats = Array.isArray(info?.formats) ? info.formats : [];
      const audio = pickYtDlpAudioFormat(formats);
      const muxed = pickYtDlpMuxedFormat(formats);
      if (!audio && !muxed) {
        errors.push(
          `yt_dlp_no_formats profile=${profile} proxy=${proxy || "none"}`
        );
        continue;
      }
      const source = audio || muxed;
      return {
        resolver: `yt-dlp-${profile}${proxy ? "-proxy" : ""}`,
        videoId,
        sourceUrl: source.url,
        isVideoSource: source === muxed && source !== audio,
        audio: audio
          ? {
              url: audio.url,
              bitrate: Number(audio?.abr || 0) || null,
              mimeType: audio?.ext ? `${audio.ext}` : null,
            }
          : null,
        muxed: muxed
          ? {
              url: muxed.url,
              bitrate: Number(muxed?.tbr || 0) || null,
              qualityLabel: muxed?.format_note || muxed?.resolution || null,
              mimeType: muxed?.ext ? `${muxed.ext}` : null,
            }
          : null,
        title: info?.title || null,
        author: info?.uploader || null,
      };
    } catch (error) {
      errors.push(
        `profile=${profile} proxy=${proxy || "none"}: ${String(error?.message || error)}`
      );
    }
  }
  if (errors.length) {
    const err = new Error(errors.join(" | "));
    err.code = "yt_dlp_profiles_exhausted";
    throw err;
  }
  return null;
}

async function resolveVideo(videoId) {
  const cached = readCachedResolve(videoId);
  if (cached) {
    return {
      ...cached,
      cached: true,
    };
  }

  let youtubeExplodeError = null;
  try {
    const resolved = await resolveWithYoutubeExplode(videoId);
    if (resolved) {
      const payload = {
        ...resolved,
        ytDlpError: null,
        youtubeExplodeError: null,
        cached: false,
      };
      writeCachedResolve(videoId, payload);
      return payload;
    }
  } catch (error) {
    youtubeExplodeError = String(error?.detail || error?.message || error);
    // eslint-disable-next-line no-console
    console.warn(
      `[resolver] youtube_explode_dart failed for ${videoId}: ${youtubeExplodeError}`
    );
  }

  let ytDlpError = null;
  try {
    const resolved = await resolveWithYtDlp(videoId);
    if (resolved) {
      const payload = {
        ...resolved,
        ytDlpError: null,
        youtubeExplodeError,
        cached: false,
      };
      writeCachedResolve(videoId, payload);
      return payload;
    }
  } catch (error) {
    ytDlpError = String(error?.message || error);
    // eslint-disable-next-line no-console
    console.warn(`[resolver] yt-dlp failed for ${videoId}: ${ytDlpError}`);
  }

  let info = null;
  let ytdlError = null;
  try {
    const ytdlOptions = YTDL_AGENT ? { agent: YTDL_AGENT } : undefined;
    info = await ytdl.getInfo(videoId, ytdlOptions);
  } catch (error) {
    ytdlError = String(error?.message || error);
  }

  const formats = info?.formats || [];
  const audio = pickAudioFormat(formats);
  const muxed = pickMuxedFormat(formats);

  if (!audio && !muxed) {
    const error = new Error("no_playable_formats");
    error.code = "no_playable_formats";
    error.detail = [
      youtubeExplodeError,
      ytdlError,
      ytDlpError,
      "resolver_sources_exhausted",
    ]
      .filter(Boolean)
      .join(" | ");
    throw error;
  }

  const source = audio || muxed;
  const payload = {
    resolver: "ytdl-core",
    ytDlpError,
    youtubeExplodeError,
    videoId,
    sourceUrl: source.url,
    isVideoSource: source === muxed && source !== audio,
    audio: audio
      ? {
          url: audio.url,
          bitrate: audio.audioBitrate || null,
          mimeType: audio.mimeType || null,
        }
      : null,
    muxed: muxed
      ? {
          url: muxed.url,
          bitrate: muxed.bitrate || null,
          qualityLabel: muxed.qualityLabel || null,
          mimeType: muxed.mimeType || null,
        }
      : null,
    title: info?.videoDetails?.title || null,
    author: info?.videoDetails?.author?.name || null,
    cached: false,
  };

  writeCachedResolve(videoId, payload);
  return payload;
}

function externalBaseUrl(req) {
  const protoHeader = String(req.header("x-forwarded-proto") || "")
    .split(",")[0]
    .trim();
  const hostHeader = String(req.header("x-forwarded-host") || "")
    .split(",")[0]
    .trim();
  const proto = protoHeader || req.protocol || "http";
  const host = hostHeader || req.get("host") || "";
  if (!host) return "";
  return `${proto}://${host}`;
}

function withProxyUrls(req, payload, videoId) {
  const base = externalBaseUrl(req);
  if (!base) return payload;
  const id = String(videoId || "").trim();
  if (!id) return payload;
  const qp = encodeURIComponent(id);
  return {
    ...payload,
    sourceProxyUrl: `${base}/stream?videoId=${qp}&kind=source`,
    audioProxyUrl: payload?.audio?.url
      ? `${base}/stream?videoId=${qp}&kind=audio`
      : null,
    muxedProxyUrl: payload?.muxed?.url
      ? `${base}/stream?videoId=${qp}&kind=muxed`
      : null,
  };
}

function pickStreamUrlByKind(payload, kind) {
  const safeKind = String(kind || "source").trim().toLowerCase();
  if (safeKind === "audio") {
    return String(payload?.audio?.url || "").trim();
  }
  if (safeKind === "muxed") {
    return String(payload?.muxed?.url || "").trim();
  }
  return String(payload?.sourceUrl || "").trim();
}

app.get("/health", (_req, res) => {
  res.json({
    ok: true,
    service: "vmmusic-yt-resolver",
    version: "1.3.0",
    startedAt: startedAt.toISOString(),
    now: new Date().toISOString(),
    uptimeSeconds: Math.round(process.uptime()),
    cacheTtlMs: RESOLVE_CACHE_TTL_MS,
    batchLimit: RESOLVE_BATCH_LIMIT,
    youtubeExplodeDartScript: fs.existsSync(YTEXPLODE_DART_SCRIPT),
    dartBinary: DART_BINARY,
    stems: true,
    coverAnimation: Boolean(COVER_ANIMATION_PROXY_URL),
  });
});

app.get("/resolve", authMiddleware, async (req, res) => {
  const videoId = String(req.query.videoId || "").trim();
  if (!videoId || !isValidVideoId(videoId)) {
    return res.status(400).json({ ok: false, error: "invalid_video_id" });
  }

  try {
    const payload = await resolveVideo(videoId);
    return res.json({ ok: true, ...withProxyUrls(req, payload, videoId) });
  } catch (error) {
    const code = String(error?.code || "");
    if (code === "no_playable_formats") {
      return res.status(404).json({
        ok: false,
        error: "no_playable_formats",
        detail: error?.detail || undefined,
      });
    }
    return res.status(500).json({
      ok: false,
      error: "resolve_failed",
      detail: String(error?.message || error),
    });
  }
});

app.get("/stream", authMiddleware, async (req, res) => {
  const videoId = String(req.query.videoId || "").trim();
  if (!videoId || !isValidVideoId(videoId)) {
    return res.status(400).json({ ok: false, error: "invalid_video_id" });
  }
  const kind = String(req.query.kind || "source").trim().toLowerCase();
  if (!["source", "audio", "muxed"].includes(kind)) {
    return res.status(400).json({ ok: false, error: "invalid_stream_kind" });
  }

  try {
    const payload = await resolveVideo(videoId);
    const targetUrl = pickStreamUrlByKind(payload, kind);
    if (!targetUrl) {
      return res.status(404).json({
        ok: false,
        error: "stream_not_available",
        kind,
      });
    }

    const outboundHeaders = {
      "user-agent":
        req.header("user-agent") ||
        "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
      accept: req.header("accept") || "*/*",
      connection: "keep-alive",
    };
    const range = String(req.header("range") || "").trim();
    if (range) outboundHeaders.range = range;

    const upstream = await fetch(targetUrl, { headers: outboundHeaders });
    if (!upstream.ok && upstream.status !== 206) {
      return res.status(upstream.status || 502).json({
        ok: false,
        error: "upstream_stream_failed",
        status: upstream.status || 0,
      });
    }
    if (!upstream.body) {
      return res.status(502).json({ ok: false, error: "empty_upstream_body" });
    }

    res.status(upstream.status);
    const passHeaders = [
      "content-type",
      "content-length",
      "content-range",
      "accept-ranges",
      "cache-control",
      "etag",
      "last-modified",
      "expires",
    ];
    for (const headerName of passHeaders) {
      const value = upstream.headers.get(headerName);
      if (value) res.setHeader(headerName, value);
    }
    res.setHeader("x-vmmusic-stream-proxy", "1");

    Readable.fromWeb(upstream.body).pipe(res);
  } catch (error) {
    return res.status(500).json({
      ok: false,
      error: "stream_proxy_failed",
      detail: String(error?.message || error),
    });
  }
});

app.post("/resolve/batch", authMiddleware, async (req, res) => {
  const videoIds = parseVideoIds(req.body?.videoIds);
  if (!videoIds.length) {
    return res.status(400).json({ ok: false, error: "invalid_video_ids" });
  }

  const settled = await Promise.allSettled(
    videoIds.map(async (videoId) => {
      const data = await resolveVideo(videoId);
      return { videoId, ok: true, data };
    })
  );

  const items = settled.map((entry, index) => {
    const videoId = videoIds[index];
    if (entry.status === "fulfilled") {
      return entry.value;
    }
    return {
      videoId,
      ok: false,
      error: "resolve_failed",
      detail: String(entry.reason?.message || entry.reason || "unknown_error"),
    };
  });

  const resolved = items.filter((item) => item.ok).length;
  return res.json({
    ok: true,
    total: items.length,
    resolved,
    failed: items.length - resolved,
    items,
  });
});

app.get("/info", authMiddleware, async (req, res) => {
  const videoId = String(req.query.videoId || "").trim();
  if (!videoId || !isValidVideoId(videoId)) {
    return res.status(400).json({ ok: false, error: "invalid_video_id" });
  }

  try {
    try {
      const details = await getExplodeInfo(videoId);
      return res.json({
        ok: true,
        videoId,
        title: details.title || null,
        author: details.author || null,
        channelId: details.channelId || null,
        durationSeconds: Number(details.durationSeconds || 0) || null,
        thumbnails: Array.isArray(details.thumbnails) ? details.thumbnails : [],
        isLiveContent: details.isLiveContent === true,
        publishDate: details.publishDate || null,
        viewCount: Number(details.viewCount || 0) || null,
      });
    } catch {
      // fallback to ytdl-core below
    }

    const ytdlOptions = YTDL_AGENT ? { agent: YTDL_AGENT } : undefined;
    const info = await ytdl.getBasicInfo(videoId, ytdlOptions);
    const details = info?.videoDetails;
    return res.json({
      ok: true,
      videoId,
      title: details?.title || null,
      author: details?.author?.name || null,
      channelId: details?.channelId || null,
      durationSeconds: Number(details?.lengthSeconds || 0) || null,
      thumbnails: Array.isArray(details?.thumbnails)
        ? details.thumbnails
            .map((thumb) => String(thumb?.url || "").trim())
            .filter(Boolean)
        : [],
      isLiveContent: details?.isLiveContent === true,
      publishDate: details?.publishDate || null,
      viewCount: Number(details?.viewCount || 0) || null,
    });
  } catch (error) {
    return res.status(500).json({
      ok: false,
      error: "info_failed",
      detail: String(error?.message || error),
    });
  }
});

function safeTrackId(raw) {
  const value = String(raw || "").trim().toLowerCase();
  const compact = value.replace(/[^a-z0-9_-]/g, "");
  return compact || null;
}

function sha1(input) {
  return crypto.createHash("sha1").update(input).digest("hex");
}

async function ensureDir(dirPath) {
  await fsp.mkdir(dirPath, { recursive: true });
}

async function fileExists(filePath) {
  try {
    await fsp.access(filePath, fs.constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

async function downloadToFile(url, destination) {
  const response = await fetch(url);
  if (!response.ok || !response.body) {
    throw new Error(`download_failed_status_${response.status}`);
  }
  await ensureDir(path.dirname(destination));
  await new Promise((resolve, reject) => {
    const write = fs.createWriteStream(destination);
    response.body.pipe(write);
    response.body.on("error", reject);
    write.on("error", reject);
    write.on("finish", resolve);
  });
}

async function runDemucs({ inputPath, outputRoot, model }) {
  const scriptPath = path.join(__dirname, "scripts", "stems_demucs.py");
  const args = [
    scriptPath,
    "--input",
    inputPath,
    "--output-root",
    outputRoot,
    "--model",
    model,
  ];

  await new Promise((resolve, reject) => {
    const child = spawn(STEMS_PYTHON, args, {
      cwd: __dirname,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      reject(new Error("stems_timeout"));
    }, STEMS_TIMEOUT_MS);
    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString("utf8");
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString("utf8");
    });
    child.on("error", (err) => {
      clearTimeout(timer);
      reject(err);
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      if (code !== 0) {
        reject(new Error(`demucs_failed_${code}: ${stderr || stdout}`));
        return;
      }
      try {
        const parsed = JSON.parse(stdout.trim());
        resolve(parsed);
      } catch (e) {
        reject(new Error(`demucs_output_parse_failed: ${String(e)}`));
      }
    });
  });
}

async function requestAnimatedCoverFromProxy({ trackId, sourceUrl }) {
  if (!COVER_ANIMATION_PROXY_URL) {
    throw new Error("cover_animation_not_configured");
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => {
    controller.abort();
  }, COVER_ANIMATION_TIMEOUT_MS);

  const headers = { "content-type": "application/json" };
  if (COVER_ANIMATION_PROXY_KEY) {
    headers["x-api-key"] = COVER_ANIMATION_PROXY_KEY;
    headers.authorization = `Bearer ${COVER_ANIMATION_PROXY_KEY}`;
  }

  try {
    const response = await fetch(COVER_ANIMATION_PROXY_URL, {
      method: "POST",
      headers,
      body: JSON.stringify({ trackId, sourceUrl }),
      signal: controller.signal,
    });
    if (!response.ok) {
      throw new Error(`cover_animation_proxy_status_${response.status}`);
    }
    const data = await response.json().catch(() => null);
    if (!data || typeof data !== "object") {
      throw new Error("cover_animation_proxy_invalid_json");
    }
    const animatedCoverUrl = String(
      data.animatedCoverUrl || data.url || data.output || ""
    ).trim();
    if (!animatedCoverUrl) {
      throw new Error("cover_animation_proxy_missing_url");
    }
    return animatedCoverUrl;
  } finally {
    clearTimeout(timeout);
  }
}

app.post("/stems/separate", authMiddleware, async (req, res) => {
  const sourceUrl = String(req.body?.sourceUrl || "").trim();
  const requestedTrackId = safeTrackId(req.body?.trackId);
  if (!sourceUrl) {
    return res.status(400).json({ ok: false, error: "missing_source_url" });
  }
  if (!/^https?:\/\//i.test(sourceUrl)) {
    return res.status(400).json({ ok: false, error: "invalid_source_url" });
  }

  const sourceHash = sha1(sourceUrl);
  const trackId = requestedTrackId || sourceHash.slice(0, 14);
  const cacheDir = path.join(STEMS_ROOT, "cache", trackId, sourceHash);
  const inputPath = path.join(cacheDir, "input_audio.bin");
  const instrumentalPath = path.join(cacheDir, "instrumental.wav");

  try {
    await ensureDir(cacheDir);
    if (!(await fileExists(instrumentalPath))) {
      if (!(await fileExists(inputPath))) {
        await downloadToFile(sourceUrl, inputPath);
      }
      const result = await runDemucs({
        inputPath,
        outputRoot: cacheDir,
        model: STEMS_MODEL,
      });
      const produced = String(result.instrumental_path || "").trim();
      if (!produced || !(await fileExists(produced))) {
        return res
          .status(500)
          .json({ ok: false, error: "instrumental_not_generated" });
      }
      await fsp.copyFile(produced, instrumentalPath);
    }

    const baseUrl = `${req.protocol}://${req.get("host")}`;
    const rel = path
      .relative(STEMS_ROOT, instrumentalPath)
      .replaceAll(path.sep, "/");
    return res.json({
      ok: true,
      trackId,
      instrumentalUrl: `${baseUrl}/stems-files/${rel}`,
    });
  } catch (error) {
    return res.status(500).json({
      ok: false,
      error: "stems_failed",
      detail: String(error?.message || error),
    });
  }
});

app.post("/cover/animate", authMiddleware, async (req, res) => {
  const sourceUrl = String(req.body?.sourceUrl || "").trim();
  const requestedTrackId = safeTrackId(req.body?.trackId);
  if (!sourceUrl) {
    return res.status(400).json({ ok: false, error: "missing_source_url" });
  }
  if (!/^https?:\/\//i.test(sourceUrl)) {
    return res.status(400).json({ ok: false, error: "invalid_source_url" });
  }
  if (!COVER_ANIMATION_PROXY_URL) {
    return res
      .status(501)
      .json({ ok: false, error: "cover_animation_not_configured" });
  }

  const sourceHash = sha1(sourceUrl);
  const trackId = requestedTrackId || sourceHash.slice(0, 14);

  try {
    let animatedCoverUrl = await requestAnimatedCoverFromProxy({
      trackId,
      sourceUrl,
    });
    if (/^\//.test(animatedCoverUrl)) {
      const baseUrl = `${req.protocol}://${req.get("host")}`;
      animatedCoverUrl = `${baseUrl}${animatedCoverUrl}`;
    }
    return res.json({
      ok: true,
      trackId,
      animatedCoverUrl,
    });
  } catch (error) {
    return res.status(500).json({
      ok: false,
      error: "cover_animation_failed",
      detail: String(error?.message || error),
    });
  }
});

app.use((error, _req, res, _next) => {
  if (String(error?.message || "") === "cors_not_allowed") {
    return res.status(403).json({ ok: false, error: "cors_not_allowed" });
  }
  return res.status(500).json({
    ok: false,
    error: "internal_error",
    detail: String(error?.message || error),
  });
});

app.listen(PORT, () => {
  // eslint-disable-next-line no-console
  console.log(`[resolver] listening on :${PORT}`);
});
